### ISSUE TITLE
error for getting calibration output

### ISSUE THREAD

**Issue by FereshtehFeiz** [pperle/gaze-tracking-pipeline#4]
Hello, thank you for this work, I want to have an idea about how will be the output. 
I want to run the code in the colab: 
https://colab.research.google.com/drive/1LvhTnsOw3MnVR5YDOP8euNbcpMvzdUC8?usp=sharing
to get the calibration_matrix.yaml  file, while I got this below error: 
``
[ WARN:0] global /tmp/pip-req-build-7m_g9lbm/opencv/modules/videoio/src/cap_v4l.cpp (893) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
OpenCV: FFMPEG: tag 0x5634504d/'MP4V' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
Traceback (most recent call last):
  File "camera_calibration.py", line 103, in <module>
    record_video(width=1280, height=720, fps=30)
  File "camera_calibration.py", line 24, in record_video
    for idx, frame in enumerate(source):
  File "/content/gaze-tracking-pipeline/webcam.py", line 30, in __iter__
    raise StopIteration
StopIteration
``
I appreciate let me know how I can fix this issue. 
Thanks

**Comment by ahmed-rebai** [comment]
hello i'm facing the same problem did you fix it ??
